version: "3.9"
services:
  api:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
    container_name: backend_api
    ports:
      - 8000:8000
    env_file:
      - ../backend/env/development/.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/home/django/app
    networks:
      - backend-api-net
      - backend-db-net
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    env_file:
      - ../backend/env/development/.db.env
    ports:
      - 5433:5432
    container_name: backend-db
    networks:
      - backend-db-net
    volumes:
      - backend-data-storage:/var/lib/postgesql/data

networks:
  backend-api-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  backend-db-net:
    driver: bridge

volumes:
  backend-data-storage:
