# Generated by Django 4.1.7 on 2023-04-04 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('chairman', 'chairman'), ('director', 'director'), ('unit manager', 'unit manager'), ('deputy unit manager', 'deputy unit manager'), ('engineer', 'engineer'), ('worker', 'worker'), ('intern', 'intern')], max_length=255)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend_api.positions')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('date_admission', models.DateField(default=datetime.date(2011, 9, 12))),
                ('email', models.EmailField(max_length=255)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.positions')),
            ],
        ),
    ]
