# Generated by Django 4.1.7 on 2023-04-04 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.staff'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_api.positions'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_admission',
            field=models.DateField(default=datetime.date(2018, 7, 17)),
        ),
    ]
